roles: ["Admin", "Moderator", Year 1", "Year 2", "Alumni", "Erasmus", "Gamer"]

categories:
  [
    "Semester 1",
    "Semester 2",
    "Semester 3",
    "Semester 4",
    "ğŸ– Chilling",
    "Study Groups",
  ]

channels: ["ğŸ’¡ï½œgetting-started"]
